const types = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  CHANGE_CART: 'CHANGE_CART',
};

export default types;
